# Generated by Django 5.0.2 on 2024-03-28 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False)),
                ('message', models.TextField()),
                ('uid1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_sender', to='chatting.user')),
                ('uid2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_reciever', to='chatting.user')),
            ],
        ),
        migrations.DeleteModel(
            name='messages',
        ),
    ]
