# Generated by Django 5.0.2 on 2024-03-31 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatting', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin2',
            old_name='uid',
            new_name='uid1',
        ),
    ]
