# Generated by Django 5.0.2 on 2024-03-29 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatting', '0002_message_delete_messages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phoneno',
            field=models.IntegerField(),
        ),
    ]
