# Generated by Django 5.0.2 on 2024-03-31 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatting', '0003_alter_admin2_uid1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='admin2',
        ),
    ]
