# Generated by Django 5.0.2 on 2024-03-31 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatting', '0004_delete_admin2'),
    ]

    operations = [
        migrations.CreateModel(
            name='admin2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('uid1', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='admin', to='chatting.user')),
            ],
        ),
    ]
