# Generated by Django 5.0.2 on 2024-04-01 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatting', '0005_admin2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='uid1',
        ),
        migrations.RemoveField(
            model_name='images',
            name='uid2',
        ),
        migrations.RemoveField(
            model_name='pin',
            name='uid1',
        ),
        migrations.RemoveField(
            model_name='pin',
            name='uid2',
        ),
        migrations.RemoveField(
            model_name='report',
            name='uid1',
        ),
        migrations.RemoveField(
            model_name='report',
            name='uid2',
        ),
        migrations.RemoveField(
            model_name='request',
            name='uid1',
        ),
        migrations.RemoveField(
            model_name='request',
            name='uid2',
        ),
        migrations.DeleteModel(
            name='block',
        ),
        migrations.DeleteModel(
            name='images',
        ),
        migrations.DeleteModel(
            name='pin',
        ),
        migrations.DeleteModel(
            name='report',
        ),
        migrations.DeleteModel(
            name='request',
        ),
    ]
