# Generated by Django 5.0.2 on 2024-03-30 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatting', '0007_alter_user_pphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pphoto',
            field=models.ImageField(default='defaultprofile.jpg', upload_to=''),
        ),
    ]
